/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author hanif
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        initData();
    }

    private void initData(){
        gameDictionary = new GameDictionary();
        gameDictionary.read("Dictionary.txt");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        algorithm = new javax.swing.ButtonGroup();
        startWord = new javax.swing.JTextField();
        targetWord = new javax.swing.JTextField();
        greedyRadio = new javax.swing.JRadioButton();
        ucsRadio = new javax.swing.JRadioButton();
        aStarRadio = new javax.swing.JRadioButton();
        solveButton = new javax.swing.JButton();
        startLabel = new javax.swing.JLabel();
        targetLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Word Ladder Solver");
        setResizable(false);

        startWord.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 18)); // NOI18N

        targetWord.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 18)); // NOI18N

        algorithm.add(greedyRadio);
        greedyRadio.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        greedyRadio.setText("GreedyBFS");
        greedyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greedyRadioActionPerformed(evt);
            }
        });

        algorithm.add(ucsRadio);
        ucsRadio.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        ucsRadio.setText("UCS");
        ucsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucsRadioActionPerformed(evt);
            }
        });

        algorithm.add(aStarRadio);
        aStarRadio.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        aStarRadio.setText("A*");
        aStarRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStarRadioActionPerformed(evt);
            }
        });

        solveButton.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        solveButton.setText("Solve");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        startLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        startLabel.setText("Start");
        startWord.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                update();
            }
            public void removeUpdate(DocumentEvent e) {
                update();
            }
            public void insertUpdate(DocumentEvent e) {
                update();
            }
        
            public void update() {
                startWordString = startWord.getText();
                System.out.println(startWordString);
            }
        });

        targetLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        targetLabel.setText("Target");
        targetWord.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                update();
            }
            public void removeUpdate(DocumentEvent e) {
                update();
            }
            public void insertUpdate(DocumentEvent e) {
                update();
            }
        
            public void update() {
                targetWordString = targetWord.getText();
                System.out.println(targetWordString);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aStarRadio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startLabel)
                                    .addComponent(targetLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(targetWord, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(startWord)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(greedyRadio)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ucsRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(solveButton)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startLabel))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetLabel))
                .addGap(32, 32, 32)
                .addComponent(greedyRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ucsRadio)
                    .addComponent(solveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aStarRadio)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        System.out.println("Start: "+startWordString);
        System.out.println("Target: "+targetWordString);
        System.out.println("Algorithm: "+algorithmString);
        BaseSolver solver = null;
        if(algorithmString!=null){
            switch (algorithmString) {
                case "GreedyBFS":
                    solver = new GreedyBFS(startWordString, targetWordString);
                    break;
                case "UCS":
                    solver = new UniformCostSearch(startWordString, targetWordString);
                    break;
                case "A*":
                    solver = new AStar(startWordString, targetWordString);
                    break;
                default:
                    break;
            }
        }
        if(solver!=null){
            solver.solve(gameDictionary);
            System.out.println(solver.getPathSolution());
            Solution.main(solver,algorithmString);
        }
    }//GEN-LAST:event_solveButtonActionPerformed

    private void greedyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greedyRadioActionPerformed
        System.out.println("GreedyBFS");
        algorithmString = "GreedyBFS";
    }//GEN-LAST:event_greedyRadioActionPerformed

    private void ucsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucsRadioActionPerformed
        System.out.println("UCS");
        algorithmString = "UCS";
    }//GEN-LAST:event_ucsRadioActionPerformed

    private void aStarRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStarRadioActionPerformed
        System.out.println("A*");
        algorithmString = "A*";
    }//GEN-LAST:event_aStarRadioActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Additional variables - added by hanif
    private GameDictionary gameDictionary;
    private String startWordString;
    private String targetWordString;
    private String algorithmString;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aStarRadio;
    private javax.swing.ButtonGroup algorithm;
    private javax.swing.JRadioButton greedyRadio;
    private javax.swing.JButton solveButton;
    private javax.swing.JLabel startLabel;
    private javax.swing.JTextField startWord;
    private javax.swing.JLabel targetLabel;
    private javax.swing.JTextField targetWord;
    private javax.swing.JRadioButton ucsRadio;
    // End of variables declaration//GEN-END:variables
}
